Create agenda list table view controller
MikePeralta27/Agenda-IOS16 pull request #1
Opened 2023-07-17 13:25 UTC by MikePeralta27

Create ContactListViewController and ContactDetailsViewController

2023-07-17 14:43 UTC, jastinmartinez requested changes

2023-07-17 14:43 UTC, jastinmartinez commented on Agenda- IOS16/Controllers/ContactDetailsViewController.swift
> +//            //create method
remove commented code

2023-07-17 14:43 UTC, jastinmartinez commented on Agenda- IOS16/Controllers/ContactDetailsViewController.swift
> +
remove space of this

2023-07-17 14:43 UTC, jastinmartinez commented on Agenda- IOS16/Controllers/ContactDetailsViewController.swift
> +//
remove all. this commented code.

2023-07-17 14:43 UTC, jastinmartinez commented on Agenda- IOS16/Controllers/ContactDetailsViewController.swift
> +
remove extra space over here.

2023-07-17 14:43 UTC, jastinmartinez commented on Agenda- IOS16/Controllers/ContactListViewController.swift
> +
remove space

2023-07-17 14:43 UTC, jastinmartinez commented on Agenda- IOS16/AppDelegate.swift
> +        let container = NSPersistentContainer(name: "DataModel")
ad an extension of this appDelegate with an enum call PersistenceKey

and should be as the following 

`enum PersistanceKey: String  {
  case Key = "DataModel"
}
`

you can used it as the following 


`let container = NSPersistentContainer(name: PersistanceKey.key.rawValue)`

2023-07-19 03:01 UTC, MikePeralta27 commented on Agenda- IOS16/AppDelegate.swift
> +        let container = NSPersistentContainer(name: "DataModel")
Addressed

2023-07-19 03:04 UTC, MikePeralta27 commented on Agenda- IOS16/Controllers/ContactDetailsViewController.swift
> +//            //create method
Commented code removed

2023-07-19 03:04 UTC, MikePeralta27 commented on Agenda- IOS16/Controllers/ContactDetailsViewController.swift
> +
Space removed

2023-07-19 03:05 UTC, MikePeralta27 commented on Agenda- IOS16/Controllers/ContactDetailsViewController.swift
> +
Extra space removed

2023-07-19 03:05 UTC, MikePeralta27 commented on Agenda- IOS16/AppDelegate.swift
> +        let container = NSPersistentContainer(name: "DataModel")
AppDelegate extension added.

2023-07-19 03:05 UTC, MikePeralta27 commented on Agenda- IOS16/Controllers/ContactListViewController.swift
> +
Space removed.

2023-07-19 03:06 UTC, MikePeralta27 commented on Agenda- IOS16/Controllers/ContactDetailsViewController.swift
> +//
Commented code removed.

2023-07-19 03:10 UTC, jastinmartinez approved these changes

2023-07-21 16:04 UTC, merged